---
- name: restart iptables
  service: name=iptables state=restarted
  async: 10
  poll: 1

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload systemd
  systemd: daemon_reload=yes
