#!/bin/bash

CONF=/etc/iptables
SBIN=/usr/sbin
UP4="${CONF}/up.ipv4.rules"
UP6="${CONF}/up.ipv6.rules"

. "${CONF}/iptables.conf"

# flush iptables (required to destroy sets)
[[ "${DEBUG}" > 0 ]] && >&2 echo "flush iptables"
. "${SBIN}/iptables-flush"

# make ipset config

# flush ipsets
[[ "${DEBUG}" > 0 ]] && >&2 echo "flush ipsets"
. "${SBIN}/ipset-flush"

# create sets
[[ "${DEBUG}" > 0 ]] && >&2 echo "create ipsets"
# ipv4 sets
/sbin/ipset create admin4           hash:ip  family inet
/sbin/ipset create server4          hash:net family inet
/sbin/ipset create custom4          hash:net family inet
/sbin/ipset create trustednet4      hash:net family inet
/sbin/ipset create private4         hash:net family inet
/sbin/ipset create private-except4  hash:net family inet
/sbin/ipset create trusted4         list:set
# ipv6 sets
/sbin/ipset create admin6           hash:ip  family inet6
/sbin/ipset create server6          hash:net family inet6
/sbin/ipset create custom6          hash:net family inet6
/sbin/ipset create trustednet6      hash:net family inet6
/sbin/ipset create private6         hash:net family inet6
/sbin/ipset create private6-except  hash:net family inet6
/sbin/ipset create trusted6         list:set
# ipv4 and ipv6 sets
/sbin/ipset create trusted          list:set
# dynamic blocking
/sbin/ipset --exist create block-ssh4           hash:ip  family inet  timeout 3600
/sbin/ipset --exist create block-ssh6           hash:ip  family inet6 timeout 3600
/sbin/ipset --exist create block-ssh            list:set
/sbin/ipset --exist create block-ssh-trusted4   hash:ip  family inet  timeout 600
/sbin/ipset --exist create block-ssh-trusted6   hash:ip  family inet6 timeout 600
/sbin/ipset --exist create block-ssh-trusted    list:set
/sbin/ipset --exist add block-ssh block-ssh4
/sbin/ipset --exist add block-ssh block-ssh6
/sbin/ipset --exist add block-ssh-trusted block-ssh-trusted4
/sbin/ipset --exist add block-ssh-trusted block-ssh-trusted6

# fill ipv4 sets
[[ "${DEBUG}" > 0 ]] && >&2 echo "fill ipv4 ipsets"

if [ -n "${NET4_ADMIN}" ] ; then
  for IP in ${NET4_ADMIN}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add admin4 ${IP}"
    /sbin/ipset add admin4 "${IP}"
  done
fi

if [ -n "${NET4_SERVER}" ] ; then
  for NET in ${NET4_SERVER}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add server4 ${NET}"
    /sbin/ipset add server4 "${NET}"
  done
fi

if [ -n "${NET4_CUSTOM}" ] ; then
  for NET in ${NET4_CUSTOM}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add custom4 ${NET}"
    /sbin/ipset add custom4 "${NET}"
  done
fi

if [ -n "${NET4_TRUSTED}" ] ; then
  for NET in ${NET4_TRUSTED}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trustednet4 ${NET}"
    /sbin/ipset add trustednet4 "${NET}"
  done
fi

if [ -n "${NET4_PRIVATE}" ] ; then
  for NET in ${NET4_PRIVATE}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add private4 ${NET}"
    /sbin/ipset add private4 "${NET}"
  done
fi

if [ -n "${NET4_PRIVATE_EXCEPT}" ] ; then
  for NET in ${NET4_PRIVATE_EXCEPT}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add private-except4 ${NET}"
    /sbin/ipset add private-except4 "${NET}"
  done
fi

[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted4 trustednet4"
/sbin/ipset --exist add trusted4 trustednet4
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted4 server4"
/sbin/ipset --exist add trusted4 server4
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted4 admin4"
/sbin/ipset --exist add trusted4 admin4

# fill ipv6 sets
[[ "${DEBUG}" > 0 ]] && >&2 echo "fill ipv6 ipsets"

if [ -n "${NET6_ADMIN}" ] ; then
  for IP in ${NET6_ADMIN}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add admin6 ${IP}"
    /sbin/ipset add admin6 "${IP}"
  done
fi

if [ -n "${NET6_SERVER}" ] ; then
  for NET in ${NET6_SERVER}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add server6 ${NET}"
    /sbin/ipset add server6 "${NET}"
  done
fi

if [ -n "${NET6_CUSTOM}" ] ; then
  for NET in ${NET6_CUSTOM}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add custom6 ${NET}"
    /sbin/ipset add custom6 "${NET}"
  done
fi

if [ -n "${NET6_TRUSTED}" ] ; then
  for NET in ${NET6_TRUSTED}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trustednet6 ${NET}"
    /sbin/ipset add trustednet6 "${NET}"
  done
fi

if [ -n "${NET6_PRIVATE}" ] ; then
  for NET in ${NET6_PRIVATE}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add private6 ${NET}"
    /sbin/ipset add private6 "${NET}"
  done
fi

if [ -n "${NET6_PRIVATE_EXCEPT}" ] ; then
  for NET in ${NET6_PRIVATE_EXCEPT}; do
    [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add private6-except ${NET}"
    /sbin/ipset add private6-except "${NET}"
  done
fi

[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted6 trustednet6"
/sbin/ipset --exist add trusted6 trustednet6
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted6 server6"
/sbin/ipset --exist add trusted6 server6
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted6 admin6"
/sbin/ipset --exist add trusted6 admin6


[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted trustednet4"
/sbin/ipset --exist add trusted trustednet4
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted trustednet6"
/sbin/ipset --exist add trusted trustednet6
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted server4"
/sbin/ipset --exist add trusted server4
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted server6"
/sbin/ipset --exist add trusted server6
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted admin4"
/sbin/ipset --exist add trusted admin4
[[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted admin6"
/sbin/ipset --exist add trusted admin6

# concat ipv4 rules
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules IPv4"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.policy"
cat "${CONF}/conf.raw.policy" > "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.rules"
cat "${CONF}/conf.raw.rules" >> "${UP4}"
echo -ne '\nCOMMIT\n\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.policy"
cat "${CONF}/conf.nat.policy" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.rules"
cat "${CONF}/conf.nat.rules" >> "${UP4}"
echo -ne '\nCOMMIT\n\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.policy"
cat "${CONF}/conf.mangle.policy" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.rules"
cat "${CONF}/conf.mangle.rules" >> "${UP4}"
echo -ne '\nCOMMIT\n\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.policy"
cat "${CONF}/conf.filter.policy" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.conntrack"
. "${CONF}/conf.filter.rules.head.conntrack" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv4.lo"
. "${CONF}/conf.filter.rules.head.ipv4.lo" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.lo"
cat "${CONF}/conf.filter.rules.head.lo" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv4.private"
. "${CONF}/conf.filter.rules.head.ipv4.private" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv4.icmp"
. "${CONF}/conf.filter.rules.head.ipv4.icmp" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ratelimit"
. "${CONF}/conf.filter.rules.head.ratelimit" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.body.ipv4"
. "${CONF}/conf.filter.rules.body.ipv4" >> "${UP4}"
echo -ne '\n' >> "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.tail.ipv4"
. "${CONF}/conf.filter.rules.tail.ipv4" >> "${UP4}"
echo -ne '\nCOMMIT\n' >> "${UP4}"

# concat ipv6 rules
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules IPv6"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.policy"
cat "${CONF}/conf.raw.policy" > "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.rules"
cat "${CONF}/conf.raw.rules" >> "${UP6}"
echo -ne '\nCOMMIT\n\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.policy"
cat "${CONF}/conf.nat.policy" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.rules"
cat "${CONF}/conf.nat.rules" >> "${UP6}"
echo -ne '\nCOMMIT\n\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.policy"
cat "${CONF}/conf.mangle.policy" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.rules"
cat "${CONF}/conf.mangle.rules" >> "${UP6}"
echo -ne '\nCOMMIT\n\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.policy"
cat "${CONF}/conf.filter.policy" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.conntrack"
. "${CONF}/conf.filter.rules.head.conntrack" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv6.lo"
. "${CONF}/conf.filter.rules.head.ipv6.lo" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.lo"
cat "${CONF}/conf.filter.rules.head.lo" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv6.private"
. "${CONF}/conf.filter.rules.head.ipv6.private" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv6.icmp"
. "${CONF}/conf.filter.rules.head.ipv6.icmp" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ratelimit"
. "${CONF}/conf.filter.rules.head.ratelimit" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.body.ipv6"
. "${CONF}/conf.filter.rules.body.ipv6" >> "${UP6}"
echo -ne '\n' >> "${UP6}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.tail.ipv6"
. "${CONF}/conf.filter.rules.tail.ipv6" >> "${UP6}"
echo -ne '\nCOMMIT\n' >> "${UP6}"

# restore rules
[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv4 rules: ${UP4}"
/sbin/iptables-restore < "${UP4}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv6 rules: ${UP6}"
/sbin/ip6tables-restore < "${UP6}"
