#!/bin/bash

CONF=/etc/iptables
SBIN=/usr/sbin
UP="${CONF}/up.rules"

# load config
. "${CONF}/iptables.conf"

# flush iptables (required to destroy sets)
[[ "${DEBUG}" > 0 ]] && >&2 echo "flush iptables"
. "${SBIN}/iptables-flush"

# flush ipsets
[[ "${DEBUG}" > 0 ]] && >&2 echo "flush ipsets"
. "${SBIN}/ipset-flush"

# create ipsets
[[ "${DEBUG}" > 0 ]] && >&2 echo "create ipsets"
. "${CONF}/conf.ipset"

# generate iptables rules
>"${UP}"
for t in raw nat mangle filter; do
  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate table ${t}"
  . "${CONF}/conf.${t}.policy" >> "${UP}"
  echo -ne '\n' >> "${UP}"
  . "${CONF}/conf.${t}.rule" >> "${UP}"
  echo -ne '\nCOMMIT\n\n' >> "${UP}"
done

# restore rules
[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv4 rules: ${UP}"
/sbin/iptables-restore < "${UP}"
[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv6 rules: ${UP}"
/sbin/ip6tables-restore < "${UP}"
